User repository implementation
Average-Rust-Enjoyers/Starbet-Live pull request #33
Opened 2023-12-20 14:42 UTC by Gitralt

2023-12-20 16:14 UTC, vaclavj requested changes

2023-12-20 16:14 UTC, vaclavj commented on src/repositories/user.rs
> +            Err(_) => return Err(BusinessLogicError::new(UserPasswordDoesNotMatch).into()),
tu by asi malo skor byt `UserDoesNotExist`

2023-12-20 16:14 UTC, vaclavj commented on src/repositories/user.rs
> +        Self::user_is_correct(user)?;
Ked sa tu ta hodnota uz dalej nepouziva tak by asi slo
```rust
Self::user_is_correct(
    Self::get_user(params.into(), &mut tx).await?
)?;
```

2023-12-30 19:35 UTC, adamvalt commented
este by to asi chcelo riesit anonymizaciu usera tak ako je to v iteracii 6

2024-01-05 15:43 UTC, Gitralt commented
> este by to asi chcelo riesit anonymizaciu usera tak ako je to v iteracii 6

zatím jsem to neřešil, uvidíme jestli to bude na něco potřeba

2024-01-05 16:26 UTC, KovacFilip approved these changes

2024-01-05 16:37 UTC, adamvalt approved these changes

2024-01-05 16:41 UTC, merged