feat: implemented the repository
Average-Rust-Enjoyers/Starbet-Live pull request #36
Opened 2023-12-20 17:52 UTC by KovacFilip

2023-12-24 13:07 UTC, adamvalt requested changes
implement GameMatchAlreadyStarted, GameMatchAlreadyFinished, GameMatchStartsAfterEnds errors

2023-12-24 13:07 UTC, adamvalt commented on src/repositories/game_match.rs
> +        }
missing GameMatchDeleted

2024-01-05 16:44 UTC, adamvalt commented
zvysne errory zatial nechame tak?

2024-01-06 10:57 UTC, KovacFilip commented
> zvysne errory zatial nechame tak?

Oh, přehlídl jsem ten comment s tím implement další errory. Ještě to dneska projdu a dodělám je tam.

2024-01-07 16:51 UTC, KovacFilip commented
@adamvalt Hele koukám na ty další errory a asi bych to zatím nechal takhle na tom isDeleted / doesNotExist.

Pak podle potřeby přidáme v budoucnu. Zatím je tohle docela abstraktní téma. Je hodně pravděpodobný, že už při testingu si něco uvědomíme a stejně to budeme nějak měnit. V tomhle PR teda zatím mergnu takovouhle kostru.

2024-01-07 16:51 UTC, KovacFilip commented
@adamvalt need approval to merge

2024-01-07 16:57 UTC, adamvalt commented
okej

2024-01-07 16:57 UTC, adamvalt approved these changes

2024-01-10 15:28 UTC, merged